# Generated by Django 3.0.7 on 2020-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201122_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
